my_string = input("Введи текст: ")
Dlina_stroki=len(my_string)
print('Введенная строка: "'+my_string+'" имеет длину:', Dlina_stroki,"символа(ов)" )
print("Строка в верхнем регистре: "+my_string.upper() )
print("Строка в нижнем регистре: "+my_string.lower())
print("Строка без пробелов: "+my_string.replace(' ',''))
print('первый символ строки: '+my_string[0])
print('последний символ строки: '+my_string[-1])