my_string = input("Введи текст: ")
Dlinna_stroki=len(my_string)
print('Введенная строка: "'+my_string+'" имеет длину:', Dlinna_stroki,"символа(ов)" )
print("Строка в верхнем регистре:")
print(my_string.upper())
print("Строка в нижнем регистре:")
print(my_string.lower())
print("Строка без пробелов:")
print(my_string.replace(' ',''))
print('первый символ строки: '+my_string[0])
print('последний символ строки: '+my_string[-1])