my_string = input("Введи текст: ")
print('Введенная строка: "'+my_string+'" имеет длину:', len(my_string),"символа(ов)" )
print("Строка в верхнем регистре: "+my_string.upper() )
print("Строка в нижнем регистре: "+my_string.lower())
print("Строка без пробелов: "+my_string.replace(' ',''))
print('Первый символ строки: '+my_string[0])
print('Последний символ строки: '+my_string[-1])